name: namer_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_pdfview: ^1.3.4
  path_provider: ^2.0.13
  dio: ^5.0.0
  url_launcher: ^6.1.4 
  carousel_slider: ^5.0.0
  excel: ^2.0.1
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image.png
    - assets/dks.png
    - assets/eks.png
    - assets/gok.png
    - assets/rec.png
    - assets/PCB.jpg
